### ISSUE TITLE
Using filtering to downscale large VirtualDisplay

### ISSUE THREAD

**Issue by nsymtex** [Regal-Internet-Brothers/autofit#2]
Sorry about making an issue but I'm not sure how to contact you best to ask your opinion on this.

I have a very large VirtualDisplay(2048, 1536)

The reason for this is to have very nice 1:1 graphics on retina iPads

But a problem is that on smaller screens jagged edges on graphics appear. It is very sad that nice graphics appear to be low quality

Here is an example of what I'm talking about http://i.imgur.com/obULHGk.png

It's this image http://i.imgur.com/rIGSX3u.png drawn on a VirtualDisplay(2048, 1536) with autofit_mojo2_demo.monkey running on my computer

I am wondering is it possible in a situation like mine to down sample the entire main display canvas to the size of the current device so that it doesn't have nearest neighbor jagged edges like this?

**Comment by nsymtex** [comment]
Maybe with shader? http://stackoverflow.com/questions/13501081/efficient-bicubic-filtering-code-in-glsl http://www.codeproject.com/Articles/236394/Bi-Cubic-and-Bi-Linear-Interpolation-with-GLSL#GLSLBiCubic

**Comment by nsymtex** [comment]
https://answers.madewithmarmalade.com/questions/23042/gpu-accelerated-high-quality-image-downsampling.html I am still looking for solution myself too

**Comment by nsymtex** [comment]
I realize now probably costs too much performance, too slow to down sample whole canvas at any non power of 2 scale. So would be better to scale down all images used per device size before using, yeah?

**Comment by ImmutableOctet** [comment]
Sorry I couldn't get back to you sooner, I was on vacation for over a week, and didn't realize you made an issue. Add upgrading to Windows 10 and being busy after New Year's, and you can see why I wasn't able to reply.

You've got the problem spot on. The only way you're going to fix this is with some kind of filtering, and that's a bit out of my comfort zone for this module. It'd be me making an extra texture and filtering it, agnostic to the user. Needless to say, I'm hesitant of doing that. Technically, this is also driver dependent. The driver dictates what's aliased, but you can definitely get around this, even if post processing is used.

**Hang on, why are we looking at it like this?** You've got the idea right, but the problem could be solved differently. Your control at a macroscopic scale may not be available without shaders, but your microscopic control is. Mojo2 images have filtering modes you can use with them. This is probably the best option for you. Simply change the filtering mode for your images, and you're good. This is for each 'Image' object, so it's up to your particular usage. You can also look into 'Image.SetFlagsMask', to control allowed flags at specific stages, or control what flags you pass when creating them.

The image below showcases each supported filtering mode at the moment. There's two modes, automatically generated mipmaps ('Image.Mipmap'), and Mojo 1's originaly filtering mode, 'Image.Filter'. This image displays each combination at 0.2 scale (Chosen so it doesn't scale uniformly):

From left to right:
1. Filter+Mipmap | 2. Filter | 3. Mipmap | 4. Nothing (0)
![filtering](https://cloud.githubusercontent.com/assets/3187882/12081004/0c18262e-b22a-11e5-86ae-d6d8f9ee0172.png)

[Source code can be found here](https://gist.github.com/ImmutableOctet/6e8e822aa9be5400df32).

I'm pretty sure these same filtering modes can be used with an 'Image' of the screen as well. If you want something more complicated, you'll need to look into post processing, though.

**Comment by nsymtex** [comment]
Hi ImmutableOctet,

I'll share with you what I'm working on in the near future. What I am trying to do is basically when the game detects a new resolution it will process and then cache all of the textures so that the processed ones can be loaded and displayed directly at the right scaled images so it looks best possible. Then next time game loads with same resolution if the textures are cached then it will load them directly and not need to process again.
